version: '3.7'

services:
  store-api:
    image: bookstore-web-api:1.0.0
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      PAYMENT_API: http://payment-gateway:8882/payment
    depends_on:
      - payment-gateway

  payment-gateway:
    image: sandokandias/stubby4j-docker
    ports:
      - "8882:8882"
    environment:
      STUBBY_PORT: 8882
    volumes:
      - ./stub/payment-gateway.yaml:/usr/local/stubby.yml:Z